### ISSUE TITLE
Use this controller on UR5e

### ISSUE THREAD

**Issue by tonkei0361** [fzi-forschungszentrum-informatik/cartesian_controllers#1]
Hello, I am trying to use this controller on UR5e and hope to get some help setting up and loading the controller to controller_manager. Felix Exner who develops Universal Robots driver told me that this controller works well with any robot that has force-torque sensor at the TCP and UR5e does have that sensor.

```
my_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "sensor_link"
    compliance_ref_link: "tool0"
    target_frame_topic: "target_frame"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

    stiffness:
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 100
        rot_y: 100
        rot_z: 100

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 0.01}
        rot_y: {p: 0.01}
        rot_z: {p: 0.01}
```

Above lines of code are from README of cartesian_controllers and I'm not sure what all links  (`end_effector_link`, `robot_base_link`, ...) and `target_frame_topic` mean. The UR driver I'm using does not seem to have those parameters, or I don't know where to find them...

Any help would be appreciated!

**Comment by stefanscherzinger** [comment]
When using one of the controllers for your specific robot, you have to adjust all link variables.
For using the URe, this could be something like the following:

```yaml
my_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool0"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

```
Finding your specific configuration is normally as follows:
1) Find out your robot's joint names. For example could you echo on /joint_states or similar. Those names should be mentioned in the controller.yaml configuration under *joints* (listed from base to tip) to tell the controller which joints it may take control of.

2) Inspect a TF tree of your robot, e.g. using RViz, and decide which TF links you plan to use in your controller. *end_effector_link* is the one that will follow your commanded motion, *robot_base_link* is used internally as a reference link for some algorithms. *ft_sensor_ref_link* is the reference frame in which you expect your force data to be given.

3) Test your configuration with SMALL gains and incrementally increase the values, e.g. using dynamic reconfigure that will be available for each controller.

I'll try to make a more in-depth *Getting started* section for setting these things up.
