### ISSUE TITLE
Simulation ignores specified controller parameters

### ISSUE THREAD

**Issue by stefanscherzinger** [fzi-forschungszentrum-informatik/cartesian_controllers#108]
**Problem description**
The simulation does not use [the specified](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/ros2/cartesian_controller_simulation/config/controller_manager.yaml) controller parameters. All controller seem to use their default implementations.

**Software versions**
 - **Commit**: dde5fdbdbfe05a2298674ccbe56616195bad8f86
 - **OS**: Ubuntu 20.04
 - **ROS version**: galactic
 - **Robot**: Happens in simulation

**To Reproduce**
Start the simulation with
```
ros2 launch cartesian_controller_simulation simulation.launch.py
```
and check the controller's parameters in `rqt` (dynamic reconfigure).

**Expected behavior**
The controllers should start with the parameters from the `.config` file.

**Additional context**
Could the dictionary initialization
```yaml
    pd_gains:
        trans_x: {p: 0.05, d: 0.005}
        trans_y: {p: 0.05, d: 0.005}
        trans_z: {p: 0.05, d: 0.005}
        rot_x: {p: 1.5}
        rot_y: {p: 1.5}
        rot_z: {p: 1.5}
```
be no longer supported in ROS2?
