### ISSUE TITLE
How can I apply this package to Gazebo model on ROS1?

### ISSUE THREAD

**Issue by soohwan-justin** [fzi-forschungszentrum-informatik/cartesian_controllers#121]
Hello @stefanscherzinger, I have tried to follow this [issue](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/47) with [UR5 gazebo model](https://github.com/ros-industrial/universal_robot/tree/kinetic).

This is my yaml and launch file

**ur_controllers.yaml**
```yaml
my_cartesian_motion_controller:
    type: "position_controllers/CartesianMotionController"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    target_frame_topic: "target_frame"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

    pd_gains:
        trans_x: {p: 10.0}
        trans_y: {p: 10.0}
        trans_z: {p: 10.0}
        rot_x: {p: 1.0}
        rot_y: {p: 1.0}
        rot_z: {p: 1.0}

my_cartesian_force_controller:
    type: "position_controllers/CartesianForceController"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool0"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

    solver:
        error_scale: 0.5

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 1.5}
        rot_y: {p: 1.5}
        rot_z: {p: 1.5}


my_cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool0"
    compliance_ref_link: "tool0"
    target_frame_topic: "target_frame"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 20
        rot_y: 20
        rot_z: 20

    solver:
        error_scale: 0.5

    pd_gains:
        trans_x: {p: 0.05}
        trans_y: {p: 0.05}
        trans_z: {p: 0.05}
        rot_x: {p: 1.50}
        rot_y: {p: 1.50}
        rot_z: {p: 1.50}

my_motion_control_handle:
   type: "cartesian_controllers/MotionControlHandle"
   end_effector_link: "tool0"
   robot_base_link: "base_link"
   target_frame_topic: "/my_cartesian_motion_controller/target_frame"
   joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

my_joint_to_cartesian_controller:
    type: "cartesian_controllers/JointControllerAdapter"
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    target_frame_topic: "/my_cartesian_motion_controller/target_frame"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

    joint_limits:
      shoulder_pan_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      shoulder_lift_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      elbow_joint:
        has_velocity_limits: true
        max_velocity: 3.15
        has_acceleration_limits: true
        max_acceleration: 10.0
      wrist_1_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      wrist_2_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0
      wrist_3_joint:
        has_velocity_limits: true
        max_velocity: 3.2
        has_acceleration_limits: true
        max_acceleration: 10.0

my_joint_to_cartesian_controller/joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

```

And my launch file is:
```XML

<launch>
        <!-- Configuration -->
        <arg name="rviz" default="true"/>
        <arg name="debug" default="false"/>
        <arg if="$(arg debug)" name="launch-prefix" value="screen -d -m gdb -command=$(env HOME)/.ros/my_debug_log --ex run --args"/>
        <arg unless="$(arg debug)" name="launch-prefix" value=""/>

        <arg name="transmission_hw_interface" default="hardware_interface/PositionJointInterface" />

        <!-- Load robot_description to parameter server -->
        <param name="/robot_description"
        command="$(find xacro)/xacro --inorder '$(find ur_description)/urdf/ur5_robot.urdf.xacro' transmission_hw_interface:=$(arg transmission_hw_interface)" />

        <!-- Load hardware configuration -->
        <!-- <rosparam file="$(find cartesian_controller_examples)/config/ur_hw_config.yaml" command="load"></rosparam> -->

        <!-- Load hardware interface -->
        <!-- <node name="sim_hardware_interface" pkg="ros_control_boilerplate" type="sim_hw_main" output="screen" launch-prefix="$(arg launch-prefix)">

                <remap from="my_motion_control_handle/target_frame" to="target_frame" />
                <remap from="my_cartesian_motion_controller/target_frame" to="target_frame" />
                <remap from="my_cartesian_compliance_controller/target_frame" to="target_frame" />

                <remap from="my_cartesian_force_controller/target_wrench" to="target_wrench" />
                <remap from="my_cartesian_compliance_controller/target_wrench" to="target_wrench" />
        </node> -->

        <!-- Robot state publisher -->
        <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
                <param name="publish_frequency" type="double" value="50.0" />
                <param name="tf_prefix" type="string" value="" />
        </node>

        <!-- Joint state publisher -->
        <node name="joint_state_controller_spawner" pkg="controller_manager" type="spawner" args="joint_state_controller" respawn="false" output="screen"/>

        <!-- Load controller configuration -->
        <rosparam file="$(find cartesian_controller_examples)/config/ur_controllers.yaml" command="load"></rosparam>

        <!-- Spawn controllers -->
        <node name="controller_spawner" pkg="controller_manager" type="spawner"
                args="--stopped
                my_cartesian_motion_controller
                my_cartesian_force_controller
                my_cartesian_compliance_controller
                my_motion_control_handle
                my_joint_to_cartesian_controller
                "
        />

        <!-- Spawn joint controller for testing my_joint_to_cartesian_controller  -->
        <!-- Note: This controller should be loaded and started -->
        <!-- <group ns="my_joint_to_cartesian_controller" >
                <node name="controller_spawner" pkg="controller_manager" type="spawner" args="joint_trajectory_controller" />
        </group> -->

        <!-- Visualization -->
        <group if="$(arg rviz)">
                <arg name="my_rviz" value="-d $(find cartesian_controller_examples)/etc/examples.rviz" />
                <node name="rviz" pkg="rviz" type="rviz" respawn="false" args="$(arg my_rviz)" output="screen" />
        </group>

        <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen"
                args="-urdf -param robot_description -model robot -unpause"> 

                <remap from="my_motion_control_handle/target_frame" to="target_frame" />
                <remap from="my_cartesian_motion_controller/target_frame" to="target_frame" />
                <remap from="my_cartesian_compliance_controller/target_frame" to="target_frame" />

                <remap from="my_cartesian_force_controller/target_wrench" to="target_wrench" />
                <remap from="my_cartesian_compliance_controller/target_wrench" to="target_wrench" />

        </node>

	<arg name="paused" default="true"/>
	<arg name="use_sim_time" default="true"/>
	<arg name="gui" default="true"/>
	<arg name="headless" default="false"/>

	<include file="$(find gazebo_ros)/launch/empty_world.launch">
		<arg name="debug" value="$(arg debug)" />
		<arg name="gui" value="$(arg gui)" />
		<arg name="paused" value="$(arg paused)"/>
		<arg name="use_sim_time" value="$(arg use_sim_time)"/>
		<arg name="headless" value="$(arg headless)"/>
	</include> 
</launch>


```

But when I run this launch file, the robot model oscillates and doesn't work even I set the parameters on rqt, like this:
![Peek 2023-03-22 21-16](https://user-images.githubusercontent.com/70736349/226902904-168e3df1-d8f4-474c-bdb4-db37aee27299.gif)

I tried to run this launch file without below lines like the[ issue](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/47), but it still doesn't work
```XML
                <remap from="my_cartesian_force_controller/target_wrench" to="target_wrench" />
                <remap from="my_cartesian_compliance_controller/target_wrench" to="target_wrench" />
```

I don't know what mistake have I made, I just want to sync the rviz and gazebo model. I hope you help me, please.
