### ISSUE TITLE
Use velocity_controllers to control the velocity on UR5

### ISSUE THREAD

**Issue by YummyOu** [fzi-forschungszentrum-informatik/cartesian_controllers#16]
Hi, I 'm using Ubuntu16.04 and ROS kinetic to teleoperate an UR5 CB3 with Universal_Robots_ROS_Driver and fmauch/universal_robot.
I use a force sensor on end-effector and would like to compute the cartesian velocity by the force info and publish the velocity to control the robot.

But I read the document and issues, there are few information about `velocity_controllers`

In one of your commit[ Controller Test: Remove velocity_controllers/CartesianMotionController](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/commit/aa4dcff31955ad3e359762ad2b84621d0b523e25), you said
> This type is not tested well enough.

```yaml
   my_cartesian_motion_controller_vel:
      type: "velocity_controllers/CartesianMotionController"
      end_effector_link: "sensor_link"
      robot_base_link: "base_link"
      target_frame: "my_target"
      joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    pid_gains:
        trans_x: {p: 5.0, i: 0, d: 0}
        trans_y: {p: 5.0, i: 0, d: 0}
        trans_z: {p: 5.0, i: 0, d: 0}
        rot_x: {p: 1.0, i: 0, d: 0}
        rot_y: {p: 1.0, i: 0, d: 0}
        rot_z: {p: 1.0, i: 0, d: 0}

```

I have 2 questions:
1. how could I use `velocity_controllers`, or is that usable or good enough now? And which topic could I use for publishing?
2. which type should I use, `CartesianMotionController` or `CartesianForceController`?
