### ISSUE TITLE
Random Jerk/trembling during execution with cartesian_motion_controller

### ISSUE THREAD

**Issue by shrutichakraborty** [fzi-forschungszentrum-informatik/cartesian_controllers#208]
**Problem description**
Hi authors, 

I have been using the all the controllers, tested both on ros1 noetic with UR10E and on ROS2 humble version with a different UR10E robot, for a while now for different use cases and have experienced some issues that I wanted to raise that might help make future improvements to the controllers. 

1. Random Jerk/trembling during execution with cartesian_motion_controller 

 - In my use case I require long continuous use of the cartesian_motion_control (about an hour) during which the robot uses a external attached camera to perform some processing and then move accordingly. I have noticed that the further the distance between the robot's current and target destination, the faster the robot moves towards the target destination and the start is not smooth, i.e the robot make an abrupt movement to move towards the destination. For this I have tried to tweak the P gains for the controller in XY direction and the error_scale but I still notice the same problem. When the target point to move is closer to the current robot position the motion is acceptable and the robot moves without a sudden jerk at start. 
 
I am wondering if this has been noticed by others before and if there is any advice to avoid this behaviour? I am also wondering if there is a possibility to allow users to control the velocity of the motion which might be like a scale factor to avoid big jerky motions? 

 -  Another issue I have faced is, often during the image processing part of my pipeline, the cartesian_motion_controller is still active and the external control on the robot is active too butthe robot is still. In this case with increased duration of running, I see the robot make sudden random jerks (even when no commands are being sent ).. I am not sure why this occurs and a fix would be greatly helpful as currently this tends to affect my image processing pipeline as the camera images come out blurry due to the robot having randomly moved. 
 
 - Finally, with the cartesian_motion_controller, if I stop the robot launch file, without first stopping external control , I notice that the robot starts moving randomly. I have been taking care to properly switch the cartesian_controller off and cutting of extrenal control to the UR before stopping the launch file on the PC but still this is a strange issue and  a fix would be really helpful. 
 
3. Precision error with cartesian_compliance_controller 
- I tested commanding a set of known positions to the robot in compliant mode to check its precision. On comparing the position reached by the robot vs the position commanded I have noticed an error in precision of about 4-7 mm in the 3 axes. Is this something to be expected? 

- Additionally, I also tried using the controller for teleoperating in compliance mode. I am sending a wrench (computed from positions and velocity of my teleop device) and the current robot position at each timestep for the teleop. However, in certain cases the robot tries to come back to its original starting position. This was also the case with the example teleop scripts with the space_nav mouse, as soon as we let go the robot returns to the center to its original start position. Whereas, what I would like is for the robot to remain where it was teleoperated to.. Anny suggestions how I could ensure this behaviour? 

I had also tried to teleop by only sending positions and that did not work as mentioned in my previous posts #194 

Here is my config for the controllers : 

```
cartesian_motion_controller:
  ros__parameters:

    # See the cartesian_compliance_controller
    end_effector_link: "tool0"
    robot_base_link: "base_link"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # See the cartesian_compliance_controller
    command_interfaces:
      - position
        #- velocity

    solver:
        error_scale: 0.9
        iterations: 12
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.6}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}
```
for the cartesian_compliance_controller I am using the base config given in the example with UR robot except the `error_scale` is at 0.25 as my robot vibrates at anything higher. 

Thanks a lot!
