### ISSUE TITLE
Implementing controllers on real UR5 robot.

### ISSUE THREAD

**Issue by minku1219** [fzi-forschungszentrum-informatik/cartesian_controllers#221]
Hi, 
I am trying to control my robot UR5 with cartesian_force_controller. On activating the controller the robot starts moving without publishing anything on wrench topic. 

My controllers.yaml :-

```
/$(var robot_name):
  controller_manager:
    ros__parameters:
      force_torque_sensor_broadcaster:
        type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

      scaled_joint_trajectory_controller:
        type: ur_controllers/ScaledJointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      cartesian_force_controller:
        type: cartesian_force_controller/CartesianForceController

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController


  force_torque_sensor_broadcaster:
    ros__parameters:
      sensor_name: $(var tf_prefix)tcp_fts_sensor
      state_interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z
      frame_id: $(var tf_prefix)tool0
      topic_name: wrench

  scaled_joint_trajectory_controller:
    ros__parameters:
      joints:
        - $(var tf_prefix)shoulder_pan_joint
        - $(var tf_prefix)shoulder_lift_joint
        - $(var tf_prefix)elbow_joint
        - $(var tf_prefix)wrist_1_joint
        - $(var tf_prefix)wrist_2_joint
        - $(var tf_prefix)wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        $(var tf_prefix)shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        $(var tf_prefix)shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        $(var tf_prefix)elbow_joint: { trajectory: 0.2, goal: 0.1 }
        $(var tf_prefix)wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        $(var tf_prefix)wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        $(var tf_prefix)wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
      speed_scaling_interface_name: $(var tf_prefix)speed_scaling/speed_scaling_factor

  cartesian_force_controller:
    ros__parameters:

      # See the cartesian_compliance_controller
      end_effector_link: "$(var tf_prefix)tool0"
      robot_base_link: "$(var tf_prefix)base_link"
      ft_sensor_ref_link: "$(var tf_prefix)tool0"
      joints:
        - $(var tf_prefix)shoulder_pan_joint
        - $(var tf_prefix)shoulder_lift_joint
        - $(var tf_prefix)elbow_joint
        - $(var tf_prefix)wrist_1_joint
        - $(var tf_prefix)wrist_2_joint
        - $(var tf_prefix)wrist_3_joint

      # See the cartesian_compliance_controller
      command_interfaces:
        - position
          #- velocity

      solver:
        error_scale: 0.2
        # publish_state_feedback: True

      pd_gains:
        trans_x: {p: 0.0}
        trans_y: {p: 0.0}
        trans_z: {p: 0.05}
        rot_x: {p: 0.0}
        rot_y: {p: 0.0}
        rot_z: {p: 0.0}

  joint_trajectory_controller:
    ros__parameters:
      joints:
        - $(var tf_prefix)shoulder_pan_joint
        - $(var tf_prefix)shoulder_lift_joint
        - $(var tf_prefix)elbow_joint
        - $(var tf_prefix)wrist_1_joint
        - $(var tf_prefix)wrist_2_joint
        - $(var tf_prefix)wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
```
