### ISSUE TITLE
Unstable cartesian force controller in Gazebo simulator

### ISSUE THREAD

**Issue by pablomalvido** [fzi-forschungszentrum-informatik/cartesian_controllers#222]
Hi experts, 

I'm trying to test the cartesian force controller in the Gazebo simulator, but as soon as I start the controller, the robot becomes very unstable, starts moving abruptly, and gets out of control. The robot I'm trying to control is a UR5 (from https://github.com/ros-industrial/universal_robot) equipped with a Robotiq Hand-e gripper end effector (from https://github.com/cambel/robotiq/tree/noetic-devel), and I'm using ROS Noetic in Ubuntu 20.04. To simulate the force-torque sensor in Gazebo, I'm using the libgazebo_ros_ft_sensor.so plugin in my URDF, with the following code:

    
    
    <gazebo reference="wrist_3_joint">
      <provideFeedback>true</provideFeedback> 
    </gazebo>
    
    <gazebo>
      <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>100.0</updateRate>
        <topicName>/my_cartesian_force_controller/ft_sensor_wrench</topicName>
        <jointName>wrist_3_joint</jointName>
        <gaussianNoise>0.0</gaussianNoise>
      </plugin>
    </gazebo>

This sensor publishes WrenchStamped messages in the /my_cartesian_force_controller/ft_sensor_wrench topic. Below, you can find the configuration I'm using for the controller:

```
my_cartesian_force_controller:
  type: "position_controllers/CartesianForceController"
  end_effector_link: "hande_tcp"
  robot_base_link: "base_link"
  ft_sensor_ref_link: "wrist_3_link"
  joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  solver:
      error_scale: 0.5
  pd_gains:
      trans_x: {p: 0.05}
      trans_y: {p: 0.05}
      trans_z: {p: 0.05}
      rot_x: {p: 1.5} 
      rot_y: {p: 1.5} 
      rot_z: {p: 1.5} 
  # In robot_base_link.
  gravity:
    x: 0
    y: 0
    z: -9.8
  tool:
    # Mass of everything that's mounted after the sensor.
    mass: 1.12785
    # The center of mass in the ft_sensor_ref_link.
    # Take a measure and try to estimate that as good as possible.
    com_x: 0.0
    com_y: 0.0
    com_z: 0.0575
```

You can also see the structure of the robot in the image below, I have highlighted the end_effector_link (blue), robot_base_link (yellow), and ft_sensor_ref_link (green).

![Image](https://github.com/user-attachments/assets/c512aa71-f2ad-4d79-9402-1f675efc95a0)

I tried different configurations, such as changing the PID values, reducing the solver error_scale, taring the simulated sensor readings before starting the controller (with additional logic), setting gravity to 0 in the controller configuration file, etc. Some of these tests worked better than others (specially when reducing a lot the error scale and reducing the P gains for the rotations), but none of them worked correctly. In the following video, you can see the robot behavior, using the previous configuration YAML file, and after following these steps:

1. Load the controller
2. Tare sensor readings
3. rosservice call /my_cartesian_force_controller/signal_taring "{}"
4. Start controller

https://github.com/user-attachments/assets/9adbbd6b-015d-4987-9fb1-a7822932df48

Moreover, the cartesian motion controller works perfectly in Gazebo using the same URDF description.

Any support you can provide would be very much appreciated. Thank you in advance.

Pablo
