### ISSUE TITLE
Applying cartesian_controllers to a robot not support ros_controllers

### ISSUE THREAD

**Issue by graziegrazie** [fzi-forschungszentrum-informatik/cartesian_controllers#28]
I'm planning to apply cartesian_compliance_controller to [Nextage Open](http://wiki.ros.org/rtmros_nextage), an upper-body humanoid. The robot does not support ros_controllers to access hardware, but supports [moveit_commander.](http://wiki.ros.org/moveit_commander) In this case, which module of the cartesian_compliance_controller should I change to adapt the robot?

As far as I checked, hardware access to get and set each joint position is performed via a joint handle. So, I guess that if I change the joint handle part with moveit_commander, I can apply the controller to the robot. 

Any suggestion is helpful for me. Thank you in advance.

**Comment by stefanscherzinger** [comment]
@graziegrazie 

If this is still relevant for you, you could have a look at [this controller.](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/tree/master/joint_to_cartesian_controller#joint-to-cartesian-controller). The idea is to connect `moveit_commander` (or Moveit) to the controller's personal `joint_trajectory_controller` and turn that into a target pose for the `cartesian_compliance_controller`.

**Comment by graziegrazie** [comment]
@stefanscherzinger 

Thank you for your suggestions! Yes, this is still relevant for me. I'm sorry for my late response because I am being taken my time for another part in the same project. It is closing, so I will concentrate on this controller soon. I may ask you some questions.

**Comment by graziegrazie** [comment]
Thanks to @stefanscherzinger's suggestion, I have successfully applied cartesian_motion_controller to Nextage Open.

Next, I'm trying cartesian_force_controller. Then, I have a question about how I should set /target_wrench (= target) and /ft_sensor_wrench (= measurement) ?

I'd like to make the robot imitate a recorded human motion of a roller painting. While recording, the human uses a roller brush with a 6D force sensor. The robot holds the same roller for motion imitation. The target and the measurement are derived from the sensor, and represented on the same frame. As the frame, I assume that end-effector link is used. I hope that , with cartesian_force_controller, the robot moves to make error zero between the target and the measurement. 

I changed cartesian_force_controller like the link below. Since I set m_hand_frame_control as false, the target is used as-is. The measurement is also used as-is because transformation in ftSensorWrenchCallback is commented out. Then, an error is computed as the target minus the measurement. With this change, I expected that the robot moves to decrease the error. However, the robot moved independently of the error.

https://github.com/graziegrazie/cartesian_controllers/blob/master/cartesian_force_controller/include/cartesian_force_controller/cartesian_force_controller.hpp

**Comment by stefanscherzinger** [comment]
@graziegrazie 

> I have successfully applied cartesian_motion_controller to Nextage Open.

Good to hear that it works!

> I changed cartesian_force_controller like the link below

Hm, that's normally not required when applying the controller to a custom robot. Is there a reason why you started to modify on source code level instead of parameterizing the controller with `URDF` links? Is there some challenge involved that I'm not aware of? Thank's for providing the changes on github, though.

From the use case you described, I think it should be possible to parameterize this accordingly. Note that your `URDF` link for the sensor must be part of the robotic chain from base to tip, as explained [here](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/issues/32#issue-1058676737). 

I'll try to provide some additional tips:

```yaml
my_cartesian_force_controller:
    type: "position_controllers/CartesianForceController"

    # This is the tip of the robot tool that you want to use for your task.
    # In your use case, I would specify a URDF link that coincides with the roller for painting.
    # E.g. the z-axis along the roller axis and the x or y-axis normal to it for applying paint to
    # some to some surface. When you specify a target_wrench, i.e. some additional forces
    # that your robot should apply to its environment, that target_wrench gets applied in this frame.
    # The idea is to specify some pushing force that makes sense for your roller painting tool.
    end_effector_link: "tool0"


    # This is usually the link directly before the first actuated joint.
    # The controller will build a kinematic chain from this link up to end_effector_link.
    # It's also the reference frame for the superposition of error components in all controllers.
    robot_base_link: "base_link"

    # This is the URDF link of your sensor. Sensor signals are assumed to be given in this frame
    # (which is also what you mentioned above). It's important that this link is located somewhere
    # between end_effector_link and robot_base_link. Make sure to specify a chain and see issue #32.
    ft_sensor_ref_link: "sensor_link"
```

On a higher level: Have you thought about using the `cartesian_compliance_controller` for that? This controller inherits both the `cartesian_motion_controller` *and* the `cartesian_force_controller`, and offers both interfaces for specifying user targets (motion and force-torque targets). I'm thinking because painting is normally also motion to a big part, and the force component is rather for making controlled contact.
