### ISSUE TITLE
Tool COM frame

### ISSUE THREAD

**Issue by captain-yoshi** [fzi-forschungszentrum-informatik/cartesian_controllers#70]
In what frame does the tool COM belongs to ? I presume it is from the `end_effector_link` parameter. 

My end effector configuration is a dual gripper. I would like the closed gripper fingertips (e.g. the `robotiq_2f140_tcp` link) to apply a force in a direction. If I set it that way, the COM frame is invalid (if my assumption is correct).

``` yaml
my_cartesian_force_controller:
    type: "position_controllers/CartesianForceController"
    com_link: "tool0" # <-- should another link be added for COM like so
    end_effector_link: "robotiq_2f140_tcp"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "robotiq_ft300_sensor"

    tool:
      mass: 2.12 # kg
      com_x: -0.024
      com_y: 0.0
      com_z: 0.0923

```

![image](https://user-images.githubusercontent.com/32679594/184980632-45cf869e-fec5-4132-b9ce-63f438676fa4.png)
